# Compass to Map - Fabric 1.21.11 build
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.11
yarn_mappings=1.21.11+build.1
loader_version=0.19.3
fabric_version=0.141.4+1.21.11

mod_id=compasstomap
mod_name=Compass to Map
mod_license=MIT
mod_version=2.0.3
mod_group_id=com.kuronami.compasstomap
mod_authors=KURONAMI
mod_description=Auto-register Explorer's Compass / Nature's Compass discoveries as JourneyMap waypoints (Fabric 1.21.11).

fcap_version=uXrWPsCu
ec_version=aS4au8gn
nc_version=7w8oJxSS
jm_version=rKAciRHz
